### ISSUE TITLE
TW_GR_E2_EoTDS Write-UP 

### ISSUE THREAD

**Issue by EavenSheets** [LFlare/picoctf_2017_writeup#1]
Could you be more specific with this explanation? It's very difficult to understand. I can get the spatula inside of the area, however, after that I am unable to get him to move properly around the first corner without returning to the entrance.

**Comment by LFlare** [comment]
@EavenSheets, it is hard to be more specific but in general, the AI prevents the spatula from turning around once it has started down a corridor, which means once it is moving up the corridor next to you, you have to move down immediately to trick it's pathfinding AI to getting the flag for you.
